# Generated by Django 6.0.6 on 2026-06-22 17:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SermonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group_type', models.CharField(choices=[('series', 'Series'), ('theme', 'Theme'), ('topic', 'Topic'), ('book', 'Book'), ('author', 'Author'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='constable', max_length=100)),
                ('book', models.CharField(max_length=100)),
                ('chapter', models.IntegerField()),
                ('verse_start', models.IntegerField()),
                ('verse_end', models.IntegerField(blank=True, null=True)),
                ('note_text', models.TextField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['book', 'chapter', 'verse_start'],
                'indexes': [models.Index(fields=['source', 'book', 'chapter', 'verse_start'], name='reader_exte_source_636642_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date_preached', models.DateField()),
                ('audio_file', models.FileField(upload_to='sermons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])])),
                ('audio_duration', models.DurationField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to='reader.pastor')),
                ('groups', models.ManyToManyField(blank=True, related_name='sermons', to='reader.sermongroup')),
            ],
            options={
                'ordering': ['-date_preached'],
            },
        ),
        migrations.CreateModel(
            name='SermonNotePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('pdf_file', models.FileField(upload_to='sermon_notes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('date_created', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='pdfs', to='reader.sermongroup')),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='reader.pastor')),
                ('sermon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdfs', to='reader.sermon')),
            ],
            options={
                'verbose_name': 'Sermon Note PDF',
                'verbose_name_plural': 'Sermon Note PDFs',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='PastorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100)),
                ('chapter', models.IntegerField()),
                ('verse_start', models.IntegerField()),
                ('verse_end', models.IntegerField(blank=True, null=True)),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='reader.sermon')),
            ],
            options={
                'ordering': ['book', 'chapter', 'verse_start'],
                'indexes': [models.Index(fields=['book', 'chapter', 'verse_start'], name='reader_past_book_8ffbc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListeningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('current_position', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='reader.sermon')),
            ],
            options={
                'verbose_name_plural': 'Listening Progress',
                'indexes': [models.Index(fields=['browser_fingerprint', 'sermon'], name='reader_list_browser_d366ec_idx')],
                'unique_together': {('browser_fingerprint', 'sermon')},
            },
        ),
        migrations.CreateModel(
            name='PDFPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100)),
                ('chapter', models.IntegerField()),
                ('verse_start', models.IntegerField()),
                ('verse_end', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='reader.sermonnotepdf')),
            ],
            options={
                'ordering': ['order', 'book', 'chapter', 'verse_start'],
                'indexes': [models.Index(fields=['pdf', 'order'], name='reader_pdfp_pdf_id_4047be_idx'), models.Index(fields=['book', 'chapter'], name='reader_pdfp_book_9120dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='SermonPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100)),
                ('chapter', models.IntegerField()),
                ('verse_start', models.IntegerField()),
                ('verse_end', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='reader.sermon')),
            ],
            options={
                'ordering': ['order', 'book', 'chapter', 'verse_start'],
                'indexes': [models.Index(fields=['sermon', 'order'], name='reader_serm_sermon__41e64b_idx'), models.Index(fields=['book', 'chapter'], name='reader_serm_book_001ca9_idx')],
            },
        ),
    ]
