# Generated by Django 6.0.6 on 2026-06-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('book', models.CharField(max_length=100)),
                ('chapter', models.IntegerField(default=1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Reading Progress',
            },
        ),
    ]
