# Generated by Django 6.0.6 on 2026-06-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_reading_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='version',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
