# Generated by Django 6.0.6 on 2026-06-30 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_reading_progress_note_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(max_length=255, upload_to='sermons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])]),
        ),
    ]
